//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetrixSisClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    using System.ComponentModel.DataAnnotations;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Animal", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca")]
    [System.SerializableAttribute()]
    public partial class Animal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PetrixSisClient.ServiceReference1.Anuncio[] AnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_animalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_animalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PetrixSisClient.ServiceReference1.Anuncio[] Anuncio {
            get {
                return this.AnuncioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnuncioField, value) != true)) {
                    this.AnuncioField = value;
                    this.RaisePropertyChanged("Anuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_animal {
            get {
                return this.ds_animalField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_animalField, value) != true)) {
                    this.ds_animalField = value;
                    this.RaisePropertyChanged("ds_animal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        [Key]
        public int id_animal {
            get {
                return this.id_animalField;
            }
            set {
                if ((this.id_animalField.Equals(value) != true)) {
                    this.id_animalField = value;
                    this.RaisePropertyChanged("id_animal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Anuncio", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca")]
    [System.SerializableAttribute()]
    public partial class Anuncio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PetrixSisClient.ServiceReference1.Animal AnimalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PetrixSisClient.ServiceReference1.Imagem_Anuncio[] Imagem_AnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PetrixSisClient.ServiceReference1.Localidade LocalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PetrixSisClient.ServiceReference1.Usuario UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string conteudo_anunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> data_anunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string email_anunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> fk_Animal_id_animalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> fk_Localidade_id_localField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> fk_Usuario_id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_anunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefone_anunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titulo_anunField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PetrixSisClient.ServiceReference1.Animal Animal {
            get {
                return this.AnimalField;
            }
            set {
                if ((object.ReferenceEquals(this.AnimalField, value) != true)) {
                    this.AnimalField = value;
                    this.RaisePropertyChanged("Animal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PetrixSisClient.ServiceReference1.Imagem_Anuncio[] Imagem_Anuncio {
            get {
                return this.Imagem_AnuncioField;
            }
            set {
                if ((object.ReferenceEquals(this.Imagem_AnuncioField, value) != true)) {
                    this.Imagem_AnuncioField = value;
                    this.RaisePropertyChanged("Imagem_Anuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PetrixSisClient.ServiceReference1.Localidade Localidade {
            get {
                return this.LocalidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadeField, value) != true)) {
                    this.LocalidadeField = value;
                    this.RaisePropertyChanged("Localidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PetrixSisClient.ServiceReference1.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string conteudo_anun {
            get {
                return this.conteudo_anunField;
            }
            set {
                if ((object.ReferenceEquals(this.conteudo_anunField, value) != true)) {
                    this.conteudo_anunField = value;
                    this.RaisePropertyChanged("conteudo_anun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> data_anun {
            get {
                return this.data_anunField;
            }
            set {
                if ((this.data_anunField.Equals(value) != true)) {
                    this.data_anunField = value;
                    this.RaisePropertyChanged("data_anun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email_anun {
            get {
                return this.email_anunField;
            }
            set {
                if ((object.ReferenceEquals(this.email_anunField, value) != true)) {
                    this.email_anunField = value;
                    this.RaisePropertyChanged("email_anun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> fk_Animal_id_animal {
            get {
                return this.fk_Animal_id_animalField;
            }
            set {
                if ((this.fk_Animal_id_animalField.Equals(value) != true)) {
                    this.fk_Animal_id_animalField = value;
                    this.RaisePropertyChanged("fk_Animal_id_animal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> fk_Localidade_id_local {
            get {
                return this.fk_Localidade_id_localField;
            }
            set {
                if ((this.fk_Localidade_id_localField.Equals(value) != true)) {
                    this.fk_Localidade_id_localField = value;
                    this.RaisePropertyChanged("fk_Localidade_id_local");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> fk_Usuario_id_user {
            get {
                return this.fk_Usuario_id_userField;
            }
            set {
                if ((this.fk_Usuario_id_userField.Equals(value) != true)) {
                    this.fk_Usuario_id_userField = value;
                    this.RaisePropertyChanged("fk_Usuario_id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        [Key]
        public int id_anun {
            get {
                return this.id_anunField;
            }
            set {
                if ((this.id_anunField.Equals(value) != true)) {
                    this.id_anunField = value;
                    this.RaisePropertyChanged("id_anun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefone_anun {
            get {
                return this.telefone_anunField;
            }
            set {
                if ((object.ReferenceEquals(this.telefone_anunField, value) != true)) {
                    this.telefone_anunField = value;
                    this.RaisePropertyChanged("telefone_anun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo_anun {
            get {
                return this.titulo_anunField;
            }
            set {
                if ((object.ReferenceEquals(this.titulo_anunField, value) != true)) {
                    this.titulo_anunField = value;
                    this.RaisePropertyChanged("titulo_anun");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Localidade", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca")]
    [System.SerializableAttribute()]
    public partial class Localidade : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PetrixSisClient.ServiceReference1.Anuncio[] AnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_localField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_localField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PetrixSisClient.ServiceReference1.Anuncio[] Anuncio {
            get {
                return this.AnuncioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnuncioField, value) != true)) {
                    this.AnuncioField = value;
                    this.RaisePropertyChanged("Anuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_local {
            get {
                return this.ds_localField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_localField, value) != true)) {
                    this.ds_localField = value;
                    this.RaisePropertyChanged("ds_local");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_local {
            get {
                return this.id_localField;
            }
            set {
                if ((this.id_localField.Equals(value) != true)) {
                    this.id_localField = value;
                    this.RaisePropertyChanged("id_local");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PetrixSisClient.ServiceReference1.Anuncio[] AnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PetrixSisClient.ServiceReference1.Tipo TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cfp_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cnpj_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string email_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endereco_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> fk_Tipo_id_tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nome_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string site_userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PetrixSisClient.ServiceReference1.Anuncio[] Anuncio {
            get {
                return this.AnuncioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnuncioField, value) != true)) {
                    this.AnuncioField = value;
                    this.RaisePropertyChanged("Anuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PetrixSisClient.ServiceReference1.Tipo Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cfp_user {
            get {
                return this.cfp_userField;
            }
            set {
                if ((object.ReferenceEquals(this.cfp_userField, value) != true)) {
                    this.cfp_userField = value;
                    this.RaisePropertyChanged("cfp_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cnpj_user {
            get {
                return this.cnpj_userField;
            }
            set {
                if ((object.ReferenceEquals(this.cnpj_userField, value) != true)) {
                    this.cnpj_userField = value;
                    this.RaisePropertyChanged("cnpj_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email_user {
            get {
                return this.email_userField;
            }
            set {
                if ((object.ReferenceEquals(this.email_userField, value) != true)) {
                    this.email_userField = value;
                    this.RaisePropertyChanged("email_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endereco_user {
            get {
                return this.endereco_userField;
            }
            set {
                if ((object.ReferenceEquals(this.endereco_userField, value) != true)) {
                    this.endereco_userField = value;
                    this.RaisePropertyChanged("endereco_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> fk_Tipo_id_tipo {
            get {
                return this.fk_Tipo_id_tipoField;
            }
            set {
                if ((this.fk_Tipo_id_tipoField.Equals(value) != true)) {
                    this.fk_Tipo_id_tipoField = value;
                    this.RaisePropertyChanged("fk_Tipo_id_tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_user {
            get {
                return this.id_userField;
            }
            set {
                if ((this.id_userField.Equals(value) != true)) {
                    this.id_userField = value;
                    this.RaisePropertyChanged("id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome_user {
            get {
                return this.nome_userField;
            }
            set {
                if ((object.ReferenceEquals(this.nome_userField, value) != true)) {
                    this.nome_userField = value;
                    this.RaisePropertyChanged("nome_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string site_user {
            get {
                return this.site_userField;
            }
            set {
                if ((object.ReferenceEquals(this.site_userField, value) != true)) {
                    this.site_userField = value;
                    this.RaisePropertyChanged("site_user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Imagem_Anuncio", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca")]
    [System.SerializableAttribute()]
    public partial class Imagem_Anuncio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PetrixSisClient.ServiceReference1.Anuncio AnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string caminho_imagem_anunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> fk_Anuncio_id_anunField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_imagem_anunField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PetrixSisClient.ServiceReference1.Anuncio Anuncio {
            get {
                return this.AnuncioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnuncioField, value) != true)) {
                    this.AnuncioField = value;
                    this.RaisePropertyChanged("Anuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string caminho_imagem_anun {
            get {
                return this.caminho_imagem_anunField;
            }
            set {
                if ((object.ReferenceEquals(this.caminho_imagem_anunField, value) != true)) {
                    this.caminho_imagem_anunField = value;
                    this.RaisePropertyChanged("caminho_imagem_anun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> fk_Anuncio_id_anun {
            get {
                return this.fk_Anuncio_id_anunField;
            }
            set {
                if ((this.fk_Anuncio_id_anunField.Equals(value) != true)) {
                    this.fk_Anuncio_id_anunField = value;
                    this.RaisePropertyChanged("fk_Anuncio_id_anun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_imagem_anun {
            get {
                return this.id_imagem_anunField;
            }
            set {
                if ((this.id_imagem_anunField.Equals(value) != true)) {
                    this.id_imagem_anunField = value;
                    this.RaisePropertyChanged("id_imagem_anun");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tipo", Namespace="http://schemas.datacontract.org/2004/07/Biblioteca")]
    [System.SerializableAttribute()]
    public partial class Tipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PetrixSisClient.ServiceReference1.Usuario[] UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PetrixSisClient.ServiceReference1.Usuario[] Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_tipo {
            get {
                return this.ds_tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_tipoField, value) != true)) {
                    this.ds_tipoField = value;
                    this.RaisePropertyChanged("ds_tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        [Key]
        public int id_tipo {
            get {
                return this.id_tipoField;
            }
            set {
                if ((this.id_tipoField.Equals(value) != true)) {
                    this.id_tipoField = value;
                    this.RaisePropertyChanged("id_tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CadastrarAnimal", ReplyAction="http://tempuri.org/IService1/CadastrarAnimalResponse")]
        void CadastrarAnimal(PetrixSisClient.ServiceReference1.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CadastrarAnimal", ReplyAction="http://tempuri.org/IService1/CadastrarAnimalResponse")]
        System.Threading.Tasks.Task CadastrarAnimalAsync(PetrixSisClient.ServiceReference1.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirAnimal", ReplyAction="http://tempuri.org/IService1/ExcluirAnimalResponse")]
        void ExcluirAnimal(PetrixSisClient.ServiceReference1.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ExcluirAnimal", ReplyAction="http://tempuri.org/IService1/ExcluirAnimalResponse")]
        System.Threading.Tasks.Task ExcluirAnimalAsync(PetrixSisClient.ServiceReference1.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarAnimal", ReplyAction="http://tempuri.org/IService1/ListarAnimalResponse")]
        PetrixSisClient.ServiceReference1.Animal[] ListarAnimal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarAnimal", ReplyAction="http://tempuri.org/IService1/ListarAnimalResponse")]
        System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Animal[]> ListarAnimalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarAnimal", ReplyAction="http://tempuri.org/IService1/BuscarAnimalResponse")]
        PetrixSisClient.ServiceReference1.Animal[] BuscarAnimal(PetrixSisClient.ServiceReference1.Animal ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarAnimal", ReplyAction="http://tempuri.org/IService1/BuscarAnimalResponse")]
        System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Animal[]> BuscarAnimalAsync(PetrixSisClient.ServiceReference1.Animal ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarAnimal", ReplyAction="http://tempuri.org/IService1/AtualizarAnimalResponse")]
        void AtualizarAnimal(PetrixSisClient.ServiceReference1.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarAnimal", ReplyAction="http://tempuri.org/IService1/AtualizarAnimalResponse")]
        System.Threading.Tasks.Task AtualizarAnimalAsync(PetrixSisClient.ServiceReference1.Animal animal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CadastrarAnuncio", ReplyAction="http://tempuri.org/IService1/CadastrarAnuncioResponse")]
        void CadastrarAnuncio(PetrixSisClient.ServiceReference1.Anuncio anu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CadastrarAnuncio", ReplyAction="http://tempuri.org/IService1/CadastrarAnuncioResponse")]
        System.Threading.Tasks.Task CadastrarAnuncioAsync(PetrixSisClient.ServiceReference1.Anuncio anu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletarAnuncio", ReplyAction="http://tempuri.org/IService1/DeletarAnuncioResponse")]
        void DeletarAnuncio(PetrixSisClient.ServiceReference1.Anuncio anu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletarAnuncio", ReplyAction="http://tempuri.org/IService1/DeletarAnuncioResponse")]
        System.Threading.Tasks.Task DeletarAnuncioAsync(PetrixSisClient.ServiceReference1.Anuncio anu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarAnuncio", ReplyAction="http://tempuri.org/IService1/ListarAnuncioResponse")]
        PetrixSisClient.ServiceReference1.Anuncio[] ListarAnuncio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarAnuncio", ReplyAction="http://tempuri.org/IService1/ListarAnuncioResponse")]
        System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Anuncio[]> ListarAnuncioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarAnuncio", ReplyAction="http://tempuri.org/IService1/BuscarAnuncioResponse")]
        PetrixSisClient.ServiceReference1.Anuncio[] BuscarAnuncio(PetrixSisClient.ServiceReference1.Anuncio anu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarAnuncio", ReplyAction="http://tempuri.org/IService1/BuscarAnuncioResponse")]
        System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Anuncio[]> BuscarAnuncioAsync(PetrixSisClient.ServiceReference1.Anuncio anu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarAnuncioDatas", ReplyAction="http://tempuri.org/IService1/ListarAnuncioDatasResponse")]
        PetrixSisClient.ServiceReference1.Anuncio[] ListarAnuncioDatas(PetrixSisClient.ServiceReference1.Anuncio anuDtMin, PetrixSisClient.ServiceReference1.Anuncio anuDtMax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarAnuncioDatas", ReplyAction="http://tempuri.org/IService1/ListarAnuncioDatasResponse")]
        System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Anuncio[]> ListarAnuncioDatasAsync(PetrixSisClient.ServiceReference1.Anuncio anuDtMin, PetrixSisClient.ServiceReference1.Anuncio anuDtMax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarAnuncio", ReplyAction="http://tempuri.org/IService1/AtualizarAnuncioResponse")]
        void AtualizarAnuncio(PetrixSisClient.ServiceReference1.Anuncio anu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarAnuncio", ReplyAction="http://tempuri.org/IService1/AtualizarAnuncioResponse")]
        System.Threading.Tasks.Task AtualizarAnuncioAsync(PetrixSisClient.ServiceReference1.Anuncio anu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarAnuncioParceiro", ReplyAction="http://tempuri.org/IService1/ListarAnuncioParceiroResponse")]
        PetrixSisClient.ServiceReference1.Anuncio[] ListarAnuncioParceiro(PetrixSisClient.ServiceReference1.Anuncio anuParceiro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarAnuncioParceiro", ReplyAction="http://tempuri.org/IService1/ListarAnuncioParceiroResponse")]
        System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Anuncio[]> ListarAnuncioParceiroAsync(PetrixSisClient.ServiceReference1.Anuncio anuParceiro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CadastrarTipo", ReplyAction="http://tempuri.org/IService1/CadastrarTipoResponse")]
        void CadastrarTipo(PetrixSisClient.ServiceReference1.Tipo tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CadastrarTipo", ReplyAction="http://tempuri.org/IService1/CadastrarTipoResponse")]
        System.Threading.Tasks.Task CadastrarTipoAsync(PetrixSisClient.ServiceReference1.Tipo tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletarTipo", ReplyAction="http://tempuri.org/IService1/DeletarTipoResponse")]
        void DeletarTipo(PetrixSisClient.ServiceReference1.Tipo tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletarTipo", ReplyAction="http://tempuri.org/IService1/DeletarTipoResponse")]
        System.Threading.Tasks.Task DeletarTipoAsync(PetrixSisClient.ServiceReference1.Tipo tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTipo", ReplyAction="http://tempuri.org/IService1/ListarTipoResponse")]
        PetrixSisClient.ServiceReference1.Tipo[] ListarTipo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarTipo", ReplyAction="http://tempuri.org/IService1/ListarTipoResponse")]
        System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Tipo[]> ListarTipoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarTipo", ReplyAction="http://tempuri.org/IService1/BuscarTipoResponse")]
        PetrixSisClient.ServiceReference1.Tipo[] BuscarTipo(PetrixSisClient.ServiceReference1.Tipo ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarTipo", ReplyAction="http://tempuri.org/IService1/BuscarTipoResponse")]
        System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Tipo[]> BuscarTipoAsync(PetrixSisClient.ServiceReference1.Tipo ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarTipo", ReplyAction="http://tempuri.org/IService1/AtualizarTipoResponse")]
        void AtualizarTipo(PetrixSisClient.ServiceReference1.Tipo tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarTipo", ReplyAction="http://tempuri.org/IService1/AtualizarTipoResponse")]
        System.Threading.Tasks.Task AtualizarTipoAsync(PetrixSisClient.ServiceReference1.Tipo tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CadastrarUsuario", ReplyAction="http://tempuri.org/IService1/CadastrarUsuarioResponse")]
        void CadastrarUsuario(PetrixSisClient.ServiceReference1.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CadastrarUsuario", ReplyAction="http://tempuri.org/IService1/CadastrarUsuarioResponse")]
        System.Threading.Tasks.Task CadastrarUsuarioAsync(PetrixSisClient.ServiceReference1.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletarUsuario", ReplyAction="http://tempuri.org/IService1/DeletarUsuarioResponse")]
        void DeletarUsuario(PetrixSisClient.ServiceReference1.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletarUsuario", ReplyAction="http://tempuri.org/IService1/DeletarUsuarioResponse")]
        System.Threading.Tasks.Task DeletarUsuarioAsync(PetrixSisClient.ServiceReference1.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarUsuario", ReplyAction="http://tempuri.org/IService1/ListarUsuarioResponse")]
        PetrixSisClient.ServiceReference1.Usuario[] ListarUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarUsuario", ReplyAction="http://tempuri.org/IService1/ListarUsuarioResponse")]
        System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Usuario[]> ListarUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarUsuario", ReplyAction="http://tempuri.org/IService1/BuscarUsuarioResponse")]
        PetrixSisClient.ServiceReference1.Usuario[] BuscarUsuario(PetrixSisClient.ServiceReference1.Usuario usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarUsuario", ReplyAction="http://tempuri.org/IService1/BuscarUsuarioResponse")]
        System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Usuario[]> BuscarUsuarioAsync(PetrixSisClient.ServiceReference1.Usuario usu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarUsuario", ReplyAction="http://tempuri.org/IService1/AtualizarUsuarioResponse")]
        void AtualizarUsuario(PetrixSisClient.ServiceReference1.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AtualizarUsuario", ReplyAction="http://tempuri.org/IService1/AtualizarUsuarioResponse")]
        System.Threading.Tasks.Task AtualizarUsuarioAsync(PetrixSisClient.ServiceReference1.Usuario user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarParceiros", ReplyAction="http://tempuri.org/IService1/ListarParceirosResponse")]
        void ListarParceiros(PetrixSisClient.ServiceReference1.Usuario parceiro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarParceiros", ReplyAction="http://tempuri.org/IService1/ListarParceirosResponse")]
        System.Threading.Tasks.Task ListarParceirosAsync(PetrixSisClient.ServiceReference1.Usuario parceiro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PetrixSisClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PetrixSisClient.ServiceReference1.IService1>, PetrixSisClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CadastrarAnimal(PetrixSisClient.ServiceReference1.Animal animal) {
            base.Channel.CadastrarAnimal(animal);
        }
        
        public System.Threading.Tasks.Task CadastrarAnimalAsync(PetrixSisClient.ServiceReference1.Animal animal) {
            return base.Channel.CadastrarAnimalAsync(animal);
        }
        
        public void ExcluirAnimal(PetrixSisClient.ServiceReference1.Animal animal) {
            base.Channel.ExcluirAnimal(animal);
        }
        
        public System.Threading.Tasks.Task ExcluirAnimalAsync(PetrixSisClient.ServiceReference1.Animal animal) {
            return base.Channel.ExcluirAnimalAsync(animal);
        }
        
        public PetrixSisClient.ServiceReference1.Animal[] ListarAnimal() {
            return base.Channel.ListarAnimal();
        }
        
        public System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Animal[]> ListarAnimalAsync() {
            return base.Channel.ListarAnimalAsync();
        }
        
        public PetrixSisClient.ServiceReference1.Animal[] BuscarAnimal(PetrixSisClient.ServiceReference1.Animal ds) {
            return base.Channel.BuscarAnimal(ds);
        }
        
        public System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Animal[]> BuscarAnimalAsync(PetrixSisClient.ServiceReference1.Animal ds) {
            return base.Channel.BuscarAnimalAsync(ds);
        }
        
        public void AtualizarAnimal(PetrixSisClient.ServiceReference1.Animal animal) {
            base.Channel.AtualizarAnimal(animal);
        }
        
        public System.Threading.Tasks.Task AtualizarAnimalAsync(PetrixSisClient.ServiceReference1.Animal animal) {
            return base.Channel.AtualizarAnimalAsync(animal);
        }
        
        public void CadastrarAnuncio(PetrixSisClient.ServiceReference1.Anuncio anu) {
            base.Channel.CadastrarAnuncio(anu);
        }
        
        public System.Threading.Tasks.Task CadastrarAnuncioAsync(PetrixSisClient.ServiceReference1.Anuncio anu) {
            return base.Channel.CadastrarAnuncioAsync(anu);
        }
        
        public void DeletarAnuncio(PetrixSisClient.ServiceReference1.Anuncio anu) {
            base.Channel.DeletarAnuncio(anu);
        }
        
        public System.Threading.Tasks.Task DeletarAnuncioAsync(PetrixSisClient.ServiceReference1.Anuncio anu) {
            return base.Channel.DeletarAnuncioAsync(anu);
        }
        
        public PetrixSisClient.ServiceReference1.Anuncio[] ListarAnuncio() {
            return base.Channel.ListarAnuncio();
        }
        
        public System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Anuncio[]> ListarAnuncioAsync() {
            return base.Channel.ListarAnuncioAsync();
        }
        
        public PetrixSisClient.ServiceReference1.Anuncio[] BuscarAnuncio(PetrixSisClient.ServiceReference1.Anuncio anu) {
            return base.Channel.BuscarAnuncio(anu);
        }
        
        public System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Anuncio[]> BuscarAnuncioAsync(PetrixSisClient.ServiceReference1.Anuncio anu) {
            return base.Channel.BuscarAnuncioAsync(anu);
        }
        
        public PetrixSisClient.ServiceReference1.Anuncio[] ListarAnuncioDatas(PetrixSisClient.ServiceReference1.Anuncio anuDtMin, PetrixSisClient.ServiceReference1.Anuncio anuDtMax) {
            return base.Channel.ListarAnuncioDatas(anuDtMin, anuDtMax);
        }
        
        public System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Anuncio[]> ListarAnuncioDatasAsync(PetrixSisClient.ServiceReference1.Anuncio anuDtMin, PetrixSisClient.ServiceReference1.Anuncio anuDtMax) {
            return base.Channel.ListarAnuncioDatasAsync(anuDtMin, anuDtMax);
        }
        
        public void AtualizarAnuncio(PetrixSisClient.ServiceReference1.Anuncio anu) {
            base.Channel.AtualizarAnuncio(anu);
        }
        
        public System.Threading.Tasks.Task AtualizarAnuncioAsync(PetrixSisClient.ServiceReference1.Anuncio anu) {
            return base.Channel.AtualizarAnuncioAsync(anu);
        }
        
        public PetrixSisClient.ServiceReference1.Anuncio[] ListarAnuncioParceiro(PetrixSisClient.ServiceReference1.Anuncio anuParceiro) {
            return base.Channel.ListarAnuncioParceiro(anuParceiro);
        }
        
        public System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Anuncio[]> ListarAnuncioParceiroAsync(PetrixSisClient.ServiceReference1.Anuncio anuParceiro) {
            return base.Channel.ListarAnuncioParceiroAsync(anuParceiro);
        }
        
        public void CadastrarTipo(PetrixSisClient.ServiceReference1.Tipo tipo) {
            base.Channel.CadastrarTipo(tipo);
        }
        
        public System.Threading.Tasks.Task CadastrarTipoAsync(PetrixSisClient.ServiceReference1.Tipo tipo) {
            return base.Channel.CadastrarTipoAsync(tipo);
        }
        
        public void DeletarTipo(PetrixSisClient.ServiceReference1.Tipo tipo) {
            base.Channel.DeletarTipo(tipo);
        }
        
        public System.Threading.Tasks.Task DeletarTipoAsync(PetrixSisClient.ServiceReference1.Tipo tipo) {
            return base.Channel.DeletarTipoAsync(tipo);
        }
        
        public PetrixSisClient.ServiceReference1.Tipo[] ListarTipo() {
            return base.Channel.ListarTipo();
        }
        
        public System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Tipo[]> ListarTipoAsync() {
            return base.Channel.ListarTipoAsync();
        }
        
        public PetrixSisClient.ServiceReference1.Tipo[] BuscarTipo(PetrixSisClient.ServiceReference1.Tipo ds) {
            return base.Channel.BuscarTipo(ds);
        }
        
        public System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Tipo[]> BuscarTipoAsync(PetrixSisClient.ServiceReference1.Tipo ds) {
            return base.Channel.BuscarTipoAsync(ds);
        }
        
        public void AtualizarTipo(PetrixSisClient.ServiceReference1.Tipo tipo) {
            base.Channel.AtualizarTipo(tipo);
        }
        
        public System.Threading.Tasks.Task AtualizarTipoAsync(PetrixSisClient.ServiceReference1.Tipo tipo) {
            return base.Channel.AtualizarTipoAsync(tipo);
        }
        
        public void CadastrarUsuario(PetrixSisClient.ServiceReference1.Usuario user) {
            base.Channel.CadastrarUsuario(user);
        }
        
        public System.Threading.Tasks.Task CadastrarUsuarioAsync(PetrixSisClient.ServiceReference1.Usuario user) {
            return base.Channel.CadastrarUsuarioAsync(user);
        }
        
        public void DeletarUsuario(PetrixSisClient.ServiceReference1.Usuario user) {
            base.Channel.DeletarUsuario(user);
        }
        
        public System.Threading.Tasks.Task DeletarUsuarioAsync(PetrixSisClient.ServiceReference1.Usuario user) {
            return base.Channel.DeletarUsuarioAsync(user);
        }
        
        public PetrixSisClient.ServiceReference1.Usuario[] ListarUsuario() {
            return base.Channel.ListarUsuario();
        }
        
        public System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Usuario[]> ListarUsuarioAsync() {
            return base.Channel.ListarUsuarioAsync();
        }
        
        public PetrixSisClient.ServiceReference1.Usuario[] BuscarUsuario(PetrixSisClient.ServiceReference1.Usuario usu) {
            return base.Channel.BuscarUsuario(usu);
        }
        
        public System.Threading.Tasks.Task<PetrixSisClient.ServiceReference1.Usuario[]> BuscarUsuarioAsync(PetrixSisClient.ServiceReference1.Usuario usu) {
            return base.Channel.BuscarUsuarioAsync(usu);
        }
        
        public void AtualizarUsuario(PetrixSisClient.ServiceReference1.Usuario user) {
            base.Channel.AtualizarUsuario(user);
        }
        
        public System.Threading.Tasks.Task AtualizarUsuarioAsync(PetrixSisClient.ServiceReference1.Usuario user) {
            return base.Channel.AtualizarUsuarioAsync(user);
        }
        
        public void ListarParceiros(PetrixSisClient.ServiceReference1.Usuario parceiro) {
            base.Channel.ListarParceiros(parceiro);
        }
        
        public System.Threading.Tasks.Task ListarParceirosAsync(PetrixSisClient.ServiceReference1.Usuario parceiro) {
            return base.Channel.ListarParceirosAsync(parceiro);
        }
    }
}
